hugoblox:
  schema: "2.0"
  identity:
    name: Juan Pablo Naranjo
    type: person
    tagline: Master of Computational Data Science | Carnegie Mellon University
    description: Master of Computational Data Science (MCDS) student at CMU. My interests lie in deep learning, NLP, and AI engineering.
  theme:
    mode: system
    pack: minimal
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
